# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

# including 1950s, Apogee, Coffee, Cyberpunk, Dark, Earth, Forest, Minimal, Mr Robot, Ocean, Rose, Strawberry
theme: Ocean
# Automatically change light/dark mode based on user's preference
day_night: true
# No value = inherit font from color theme pack
# including Minimal (modern), Classic (original Academic v1 style), Rose (traditional serif), Mr Robot (futuristic), Native: use device fonts for maximum performance
font: Classic
# including xs, s, m, l, xl
font_size: L
# gravatar: true


# SEO, search engine and social network optimizations

# including Person, Organization, LocalBusiness, Project, EducationalOrganization
site_type: Person
# for LocalBusiness type
local_business_type: ''
# Defaults to the site title set in config.yaml
org_name: ''
# a description for social sharing and search engines
description: 'Jipeng Zhang Homepage including biography, publication and experience'
twitter: ''

# Site header

main_menu:
  # Display the navigation bar?
  enable: true
  # Align menu links: left (l), center (c), or right (r)
  align: l
  # Display your site title or `assets/media/logo*` image in the nav bar?
  show_logo: true
  # Show a language chooser (if you have translated your site content)?
  show_translations: false
  # If `show_translations` is enabled, do you wish to display the current language name?
  show_language: false
  # Let the user override the default light/dark mode of your theme?
  show_day_night: true
  # Let the user search from the nav bar?
  show_search: true
  # Attempt to automatically highlight the active menu link? Can be disabled for complex sites.
  highlight_active_link: true

# Localization

date_format: 'Jan 2, 2006'
time_format: '3:04 PM'

# Site features

# Code syntax highlighting
highlight: true
# Latex math
math: true
# Draw diagrams on pages using the Markdown-like Mermaid syntax
diagram: false
# about cookie and privacy
privacy_pack: false

# Let your users suggest improvements to pages
edit_page:
  repo_url: ''
  content_dir: ''
  repo_branch: main
  editable:
    page: false
    post: false
    book: false

# enable recommendations
show_related:
  book: true
  page: false
  post: true
  project: true
  publication: true
  event: true

sharing_image: ''
reading_time: true
section_pager: false
docs_section_pager: true
sharing: true

copyright_license:
  enable: false
  allow_derivatives: false
  share_alike: true
  allow_commercial: false
  notice: 'This work is licensed under {license}'

plugins_js: []
breadcrumb:
  page_types:
    book: true
comments:
  provider: ''
  commentable:
    book: true
  disqus:
    shortname: ''
    show_count: true
  commento:
    url: ''

# see https://wowchemy.com/docs/hugo-tutorials/search/
search:
  provider:
#   provider: wowchemy
#   wowchemy:
#     min_length: 1  # Only the matches whose length exceeds this value will be returned.
#     threshold: 0.3  # Where 0 requires a perfect match and 1 matches anything.
  # provider:
  # algolia:
  #   app_id: ''
  #   api_key: ''
  #   index_name: ''
  #   show_logo: false
# SEO, search engine optimization
marketing:
  google_analytics: ''
  google_tag_manager: ''
  google_site_verification: 'M-UdF2AKIRZ9gTw9pGO_7vuT7xURRTV_xeWHjNZQfro'
  bing_site_verification: '5AF29DE0415F81B1C36201B2E5A0DD39'
  baidu_site_verification: 'code-BuWT4BDGPF'

cms:
  branch: main
  local_backend: false

icon:
  pack:
    ai: false
